<a href="https://colab.research.google.com/github/muradhani/pytorch/blob/main/ch0_exercises_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2. Create a random tensor with shape (7, 7).


In [32]:
import torch 
tensor = torch.rand(7,7)
tensor , tensor.shape 

(tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
         [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
         [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
         [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
         [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
         [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
         [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]]),
 torch.Size([7, 7]))

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [33]:
tensor2 = torch.rand(1,7)
tensor2


tensor([[0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967]])

In [34]:
torch.t(tensor2)

tensor([[0.4910],
        [0.1235],
        [0.1143],
        [0.4725],
        [0.5751],
        [0.2952],
        [0.7967]])

In [35]:
tensor3 = torch.matmul(tensor , torch.t(tensor2))
tensor3

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [36]:
import torch
#set the random seed 
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)
tensor2 = torch.rand(1,7)


In [37]:
torch.matmul(tensor , torch.t(tensor2))


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [7]:
import torch 
torch.cuda.seed()
device = "cuda" if torch.cuda.is_available() else "cpu"


6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:


In [8]:
torch.manual_seed(1234)
tensor_cpu1 = torch.rand(2,3)
tensor_cpu2 = torch.rand(2,3)


In [9]:
torch.cuda.is_available()

True

In [10]:
tensor_gpu1 =tensor_cpu1.to(device)
tensor_gpu2 =tensor_cpu2.to(device)
tensor_gpu1 , tensor_gpu2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [14]:
matrixmul =torch.matmul(tensor_gpu1 , torch.t(tensor_gpu2))
matrixmul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

# 8. Find the maximum and minimum values of the output of 7.

In [15]:
torch.min(matrixmul) , torch.max(matrixmul)

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

In [16]:
torch.argmax(matrixmul) , torch.argmin(matrixmul)

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [25]:
torch.manual_seed(7)
tensor = torch.rand(1,1,1,10)
tensor , tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))

In [26]:
tensor.squeeze(),tensor.squeeze().shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]), torch.Size([10]))