<a href="https://colab.research.google.com/github/muradhani/pytorch/blob/main/pytorch_ch0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
!nvidia-smi

Wed Jan 18 16:28:49 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    29W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#0.0 pytorch funcdamentals 
import torch 
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [ ]:
#intro to tensor 
#creating tensors 
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#tensor dimension
scalar.ndim

0

In [ ]:
#get tensor item back as an intger 
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix 
MATRIX = torch.tensor([[7,7],
                      [9,10]])
MATRIX

tensor([[ 7,  7],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 7])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

this mean we got one 3 by 3 matrix 

In [ ]:
#tensor
TENSOR = torch.tensor([
    [
    [1,2,3,3],
    [4,5,6,6],
    [7,8,9,9],
    
]
])
TENSOR

tensor([[[1, 2, 3, 3],
         [4, 5, 6, 6],
         [7, 8, 9, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 4])

## Random tensors

In [ ]:
#create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0648, 0.5577, 0.4620, 0.1655],
        [0.1009, 0.2658, 0.8873, 0.0542],
        [0.9553, 0.6825, 0.6419, 0.6253]])

In [ ]:
#creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height,width,colour (RGB)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.5388, 0.6745, 0.2045],
        [0.9168, 0.3334, 0.4489],
        [0.4875, 0.5149, 0.3662]])

In [ ]:
 #creating tensor full of zeros 
 zeros = torch.zeros(size=(3,4))
 zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create tensor all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
#create range of tensors 
#torch.range
one_to_ten = torch.arange(0,11)
#to specify the step :
one_to_ten_steps = torch.arange(start = 0,end = 100,step = 2)
one_to_ten_steps

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
#tensors like the shape of another tensor
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0]
                               ,dtype=None #what data type of tensor  
                               ,device="cpu" #what device your tensor on
                               ,requires_grad=False #whether or not track gradients with this tensors operations
                               ) 

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
#getting information from tensors 
#how to check shape , data type, device 
#1- datatype tensor.dtype
#2- shape tensor.shape
#3-device tensor.device

In [ ]:
#creating a tensor 
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0342, 0.0649, 0.2046, 0.5666],
        [0.0606, 0.0161, 0.9282, 0.5751],
        [0.9412, 0.4827, 0.0903, 0.2480]])

In [ ]:
#details about tensor
print(some_tensor)
print(f"data type of tensor :{some_tensor.dtype}")
print(f"shape of tensor :{some_tensor.shape}")
print(f"device of tensor :{some_tensor.device}")

tensor([[0.0342, 0.0649, 0.2046, 0.5666],
        [0.0606, 0.0161, 0.9282, 0.5751],
        [0.9412, 0.4827, 0.0903, 0.2480]])
data type of tensor :torch.float32
shape of tensor :torch.Size([3, 4])
device of tensor :cpu


manipulating tensors ( tensor operations) 


tensor operations
* addition 
* substraction
* multiplication
* division
* matrix multiplication

In [ ]:
#creating a tensor 
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10
tensor * 10 


tensor([10, 20, 30])

In [ ]:
#substract 10 
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#pytorch bulit in functions
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
#matrix multiplication 
#two ways to perform multiplication in neural network and deeplearning : 
#1- element-wise multiplication
#2-matrix multiplication

In [ ]:
#element wise multiplication
print(tensor, '*' ,tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
#one most common error is shape error
#rules to do matrix multiplication 
#1- the inne dimension must match (3,2) * (2,6) work (3,2)* (3,2) not work (3,2) * (2,3) work
#2- the result of the matrix has shape of the outer dimension
#torch.matmul(torch.rand(3,2) , torch.rand(3,2)) error
torch.matmul(torch.rand(3,2) , torch.rand(2,3)) # ->3,3 the out dimension

tensor([[0.7624, 0.7373, 0.1813],
        [1.1919, 1.0199, 0.5796],
        [1.2748, 1.1126, 0.5713]])

finding the min max mean sum for tensor **bold text**

In [ ]:
x = torch.arange (0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.max()

(tensor(0), tensor(90))

In [ ]:
#find the max 
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
#find mean require float 32 to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum 
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [ ]:
#24 find the positional min and max of tensor
x.argmin() #this return the position of minimum argument in tensor

tensor(0)

In [ ]:
x[0] #this return the min argument

tensor(0)

In [ ]:
#find position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[x.argmax()]

tensor(90)

reshaping , stacking, squeezing and unsqueezing tesnor
1-

1. reshaping reshape an input tensor to a defined shape 
2. view return a view of an input tensor of certain shape but keep the same 
3. stacking combine multiple tensor on top of each others
4. squeez remove all '1' dimension from a tensor
5. unsqueez add a '1' dimension to a target tensor
6. permute return a view of the input with dimensions permuted (swapped)

In [ ]:
import torch 

x = torch.arange(1,10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
#add extra dimension 

x_reshaped = x.reshape(9,1) #the new shape multiply should be equal to the original size like 10 could be reshaped to 2 , 5 or 5,2 or 1 , 9 or 9,1
x_reshaped ,x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]), torch.Size([9, 1]))

In [ ]:
#change the view 
z = x.view(1,9)
z , z.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x because view of tensor shares the same memory as the original input 
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#stack tensor on top of each others 
x_stacked = torch.stack([x,x,x,x] , dim = 1 )
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
#squeez and unsqueez 
#remove all single dimensions from a target tensor
x_reshaped


tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x_reshaped.shape


torch.Size([9, 1])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_reshaped.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_reshaped

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
#selecting indexs 
import torch 
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#index on middle bracket 
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][2]

tensor(3)

In [ ]:
#: to select all the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

pytorch has functionality to interact with numpy.


*   Data in numpy want in pytorch tensor -> torch.from_numpy(ndarray)
*   pytorch tensor ->numpy -> torch.tensor.numpy()



In [ ]:
#pytorch and numpy 
#numpy array to tensor 
import torch 
import numpy as np
array = np.arange(1.0,8.0) # the deafult numpy type is float 64 
# tensor = torch.from_numpy(array)
#to change th numpy to float 32
tensor = torch.from_numpy(array).type(torch.float32) #warning when converting from numpy to tensor reflects numpy deafult datatype of float 64 unless specifies the another type

array , tensor 

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype , tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
#change value of array what will do to tensor ? 
array = array+1
array , tensor #the tensor values dont change if we change the value of the array 

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#tensor to numpy array 
tensor = torch.ones(7) #pytorch tensor deafult dtype is 32 
numpy_tensor = tensor.numpy()
tensor , numpy_tensor 

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor what happens to numpy 
tensor = tensor+1 
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducability 
# trying to take random out of random 

#neural network learns :
# start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data
# to reduce the randomness in neural networks in pytorch comes the conpcept of a **random seed**

what a random seed does is flavour the randomness.

In [ ]:
import torch

random_tensor_A =  torch.rand(3,4)
random_tensor_B =  torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7221, 0.5504, 0.7102, 0.4829],
        [0.5520, 0.3426, 0.0369, 0.2764],
        [0.3702, 0.2608, 0.6793, 0.1133]])
tensor([[0.0116, 0.3947, 0.0531, 0.2159],
        [0.9531, 0.7274, 0.6671, 0.1482],
        [0.7018, 0.1326, 0.9683, 0.0484]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch
#set the random seed 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# GPU accessiability 

In [ ]:
import torch 
torch.cuda.is_available()

True